import not_found

def test_failure():
    assert False
